/**
 * Zero Chart — Multi-Asset Instruments Registry & Watchlist Data
 * Dedicated categorized watchlists (NO "ALL" watchlist), comprehensive Indian stocks,
 * Futures, 24/7 Crypto, and Commodities.
 */

export const DEFAULT_WATCHLISTS = [
  {
    id: 'wl-stocks',
    name: 'Indian Stocks',
    symbols: [
      'MUTHOOTFIN',
      'ICICIBANK',
      'RELIANCE',
      'TCS',
      'HDFCBANK',
      'INFY',
      'TATAMOTORS',
      'SBIN',
      'AXISBANK',
      'KOTAKBANK',
      'BAJFINANCE',
      'LT',
      'ITC',
      'MARUTI',
      'TITAN',
      'ASIANPAINT',
      'SUNPHARMA',
      'TATASTEEL',
      'HAL',
      'BEL',
      'TRENT',
      'BSE',
      'CDSL',
      'JIOFIN',
    ],
  },
  {
    id: 'wl-indices',
    name: 'Indices & Futures',
    symbols: [
      'NIFTY 50',
      'BANKNIFTY',
      'FINNIFTY',
      'CNXAUTO',
      'CNXIT',
      'NIFTYMIDCAP',
      'SENSEX',
      'NIFTY FUT',
      'BANKNIFTY FUT',
    ],
  },
  {
    id: 'wl-crypto',
    name: '24/7 Crypto',
    symbols: [
      'BTCUSDT',
      'ETHUSDT',
      'SOLUSDT',
      'BNBUSDT',
      'XRPUSDT',
      'DOGEUSDT',
      'ADAUSDT',
      'LINKUSDT',
      'AVAXUSDT',
      'SUIUSDT',
    ],
  },
  {
    id: 'wl-commodities',
    name: 'Commodities & Forex',
    symbols: [
      'GOLD FUT',
      'SILVER FUT',
      'CRUDEOIL FUT',
      'NATURALGAS FUT',
      'COPPER FUT',
      'ZINC FUT',
      'ALUMINIUM FUT',
      'MCXBULLDEX',
      'MCXMETLDEX',
      'PAXGUSDT',
      'USDINR',
      'EURUSD',
      'US10Y',
    ],
  },
];

export const MASTER_INSTRUMENTS = [
  // ─── INDIAN EQUITIES ───────────────────────────────────────────────
  {
    symbol: 'MUTHOOTFIN',
    displaySymbol: 'MUTHOOTFIN',
    name: 'Muthoot Finance Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 2836.90,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'MF',
    badgeColor: '#e53935',
  },
  {
    symbol: 'ICICIBANK',
    displaySymbol: 'ICICIBANK',
    name: 'ICICI Bank Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1342.40,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'IC',
    badgeColor: '#f57c00',
  },
  {
    symbol: 'RELIANCE',
    displaySymbol: 'RELIANCE',
    name: 'Reliance Industries Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1243.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'RE',
    badgeColor: '#2962ff',
  },
  {
    symbol: 'TCS',
    displaySymbol: 'TCS',
    name: 'Tata Consultancy Services',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 2121.10,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'TC',
    badgeColor: '#7c4dff',
  },
  {
    symbol: 'HDFCBANK',
    displaySymbol: 'HDFCBANK',
    name: 'HDFC Bank Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 726.85,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'HD',
    badgeColor: '#00897b',
  },
  {
    symbol: 'INFY',
    displaySymbol: 'INFY',
    name: 'Infosys Limited',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1044.40,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'IN',
    badgeColor: '#1e88e5',
  },
  {
    symbol: 'TATAMOTORS',
    displaySymbol: 'TATAMOTORS',
    name: 'Tata Motors Ltd. (TMPV)',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 304.75,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'TM',
    badgeColor: '#e53935',
  },
  {
    symbol: 'SBIN',
    displaySymbol: 'SBIN',
    name: 'State Bank of India',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 993.30,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'SB',
    badgeColor: '#3949ab',
  },
  {
    symbol: 'AXISBANK',
    displaySymbol: 'AXISBANK',
    name: 'Axis Bank Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1244.90,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'AX',
    badgeColor: '#880e4f',
  },
  {
    symbol: 'KOTAKBANK',
    displaySymbol: 'KOTAKBANK',
    name: 'Kotak Mahindra Bank',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1845.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'KB',
    badgeColor: '#d32f2f',
  },
  {
    symbol: 'BAJFINANCE',
    displaySymbol: 'BAJFINANCE',
    name: 'Bajaj Finance Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 7120.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'BF',
    badgeColor: '#0288d1',
  },
  {
    symbol: 'LT',
    displaySymbol: 'LT',
    name: 'Larsen & Toubro Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 3876.30,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'LT',
    badgeColor: '#fbc02d',
  },
  {
    symbol: 'ITC',
    displaySymbol: 'ITC',
    name: 'ITC Limited',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 485.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'IT',
    badgeColor: '#5d4037',
  },
  {
    symbol: 'MARUTI',
    displaySymbol: 'MARUTI',
    name: 'Maruti Suzuki India',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 12179.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'MS',
    badgeColor: '#00acc1',
  },
  {
    symbol: 'SUNPHARMA',
    displaySymbol: 'SUNPHARMA',
    name: 'Sun Pharmaceutical',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1847.40,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'SP',
    badgeColor: '#f57c00',
  },
  {
    symbol: 'TITAN',
    displaySymbol: 'TITAN',
    name: 'Titan Company Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 3580.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'TT',
    badgeColor: '#7b1fa2',
  },
  {
    symbol: 'ASIANPAINT',
    displaySymbol: 'ASIANPAINT',
    name: 'Asian Paints Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 2443.20,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'AP',
    badgeColor: '#e91e63',
  },
  {
    symbol: 'TATASTEEL',
    displaySymbol: 'TATASTEEL',
    name: 'Tata Steel Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 187.48,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'TS',
    badgeColor: '#546e7a',
  },
  {
    symbol: 'HAL',
    displaySymbol: 'HAL',
    name: 'Hindustan Aeronautics',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 4860.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'HL',
    badgeColor: '#00838f',
  },
  {
    symbol: 'BEL',
    displaySymbol: 'BEL',
    name: 'Bharat Electronics Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 398.60,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'BE',
    badgeColor: '#2e7d32',
  },
  {
    symbol: 'TRENT',
    displaySymbol: 'TRENT',
    name: 'Trent Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 2799.90,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'TR',
    badgeColor: '#6a1b9a',
  },
  {
    symbol: 'BSE',
    displaySymbol: 'BSE',
    name: 'BSE Limited',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 3264.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'BS',
    badgeColor: '#c2185b',
  },
  {
    symbol: 'CDSL',
    displaySymbol: 'CDSL',
    name: 'Central Depository Services',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1373.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'CD',
    badgeColor: '#512da8',
  },
  {
    symbol: 'JIOFIN',
    displaySymbol: 'JIOFIN',
    name: 'Jio Financial Services',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 335.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'JF',
    badgeColor: '#00bcd4',
  },

  // ─── INDIAN INDICES & FUTURES ──────────────────────────────────────
  {
    symbol: 'NIFTY 50',
    displaySymbol: 'NIFTY',
    name: 'Nifty 50 Index',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 23324.90,
    tickSize: 0.05,
    precision: 2,
    badgeText: '50',
    badgeColor: '#2962ff',
  },
  {
    symbol: 'BANKNIFTY',
    displaySymbol: 'BANKNIFTY',
    name: 'Nifty Bank Index',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 56248.75,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'BK',
    badgeColor: '#1e53e5',
  },
  {
    symbol: 'FINNIFTY',
    displaySymbol: 'FINNIFTY',
    name: 'Nifty Financial Services',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 25469.10,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'FN',
    badgeColor: '#089981',
  },
  {
    symbol: 'CNXAUTO',
    displaySymbol: 'CNXAUTO',
    name: 'Nifty Auto Index',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 27232.55,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'AU',
    badgeColor: '#e040fb',
  },
  {
    symbol: 'NIFTYMIDCAP',
    displaySymbol: 'NIFTY MIDCAP',
    name: 'Nifty Midcap 50 Index',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 17784.30,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'MC',
    badgeColor: '#ff9800',
  },
  {
    symbol: 'CNXIT',
    displaySymbol: 'CNXIT',
    name: 'Nifty IT Index',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 28664.15,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'IT',
    badgeColor: '#00bcd4',
  },
  {
    symbol: 'SENSEX',
    displaySymbol: 'SENSEX',
    name: 'BSE Sensex Index',
    exchange: 'BSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 74467.15,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'SX',
    badgeColor: '#ff5252',
  },
  {
    symbol: 'NIFTY FUT',
    displaySymbol: 'NIFTY FUT',
    name: 'Nifty 50 Index Futures',
    exchange: 'NFO',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 23360.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'NF',
    badgeColor: '#2962ff',
  },
  {
    symbol: 'BANKNIFTY FUT',
    displaySymbol: 'BANKNIFTY FUT',
    name: 'Bank Nifty Futures',
    exchange: 'NFO',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 56310.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'BF',
    badgeColor: '#1e53e5',
  },

  // ─── 24/7 LIVE CRYPTO ──────────────────────────────────────────────
  {
    symbol: 'BTCUSDT',
    displaySymbol: 'BTC / USDT',
    name: 'Bitcoin',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 81300.00,
    tickSize: 0.01,
    precision: 2,
    badgeText: '₿',
    badgeColor: '#f7931a',
  },
  {
    symbol: 'ETHUSDT',
    displaySymbol: 'ETH / USDT',
    name: 'Ethereum',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 2640.00,
    tickSize: 0.01,
    precision: 2,
    badgeText: 'Ξ',
    badgeColor: '#627eea',
  },
  {
    symbol: 'SOLUSDT',
    displaySymbol: 'SOL / USDT',
    name: 'Solana',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 112.00,
    tickSize: 0.01,
    precision: 2,
    badgeText: '◎',
    badgeColor: '#14f195',
  },
  {
    symbol: 'BNBUSDT',
    displaySymbol: 'BNB / USDT',
    name: 'BNB Coin',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 765.00,
    tickSize: 0.1,
    precision: 2,
    badgeText: '🔶',
    badgeColor: '#f3ba2f',
  },
  {
    symbol: 'XRPUSDT',
    displaySymbol: 'XRP / USDT',
    name: 'Ripple',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 1.41,
    tickSize: 0.0001,
    precision: 4,
    badgeText: '✕',
    badgeColor: '#546e7a',
  },
  {
    symbol: 'DOGEUSDT',
    displaySymbol: 'DOGE / USDT',
    name: 'Dogecoin',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 0.087,
    tickSize: 0.0001,
    precision: 4,
    badgeText: 'Ð',
    badgeColor: '#c2a633',
  },
  {
    symbol: 'ADAUSDT',
    displaySymbol: 'ADA / USDT',
    name: 'Cardano',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 0.224,
    tickSize: 0.0001,
    precision: 4,
    badgeText: '₳',
    badgeColor: '#0033ad',
  },
  {
    symbol: 'LINKUSDT',
    displaySymbol: 'LINK / USDT',
    name: 'Chainlink',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 12.50,
    tickSize: 0.01,
    precision: 2,
    badgeText: '⬡',
    badgeColor: '#375bd2',
  },
  {
    symbol: 'AVAXUSDT',
    displaySymbol: 'AVAX / USDT',
    name: 'Avalanche',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 8.95,
    tickSize: 0.01,
    precision: 2,
    badgeText: '🔺',
    badgeColor: '#e84142',
  },
  {
    symbol: 'SUIUSDT',
    displaySymbol: 'SUI / USDT',
    name: 'Sui Network',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 0.835,
    tickSize: 0.0001,
    precision: 4,
    badgeText: '💧',
    badgeColor: '#4ca2fe',
  },

  // ─── MCX COMMODITIES & FUTURES (INDIA) ──────────────────────────────
  {
    symbol: 'GOLD FUT',
    displaySymbol: 'GOLD FUT',
    name: 'MCX Gold Futures (10g)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 74500.0,
    tickSize: 1.0,
    precision: 2,
    badgeText: 'GLD',
    badgeColor: '#ffd700',
  },
  {
    symbol: 'GOLDM FUT',
    displaySymbol: 'GOLDM FUT',
    name: 'MCX Gold Mini Futures (100g)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 74500.0,
    tickSize: 1.0,
    precision: 2,
    badgeText: 'GM',
    badgeColor: '#ffd700',
  },
  {
    symbol: 'SILVER FUT',
    displaySymbol: 'SILVER FUT',
    name: 'MCX Silver Futures (30kg)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 89500.0,
    tickSize: 1.0,
    precision: 2,
    badgeText: 'SLV',
    badgeColor: '#b0bec5',
  },
  {
    symbol: 'SILVERM FUT',
    displaySymbol: 'SILVERM FUT',
    name: 'MCX Silver Mini Futures (5kg)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 89500.0,
    tickSize: 1.0,
    precision: 2,
    badgeText: 'SM',
    badgeColor: '#b0bec5',
  },
  {
    symbol: 'SILVERMIC FUT',
    displaySymbol: 'SILVERMIC FUT',
    name: 'MCX Silver Micro Futures (1kg)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 89500.0,
    tickSize: 1.0,
    precision: 2,
    badgeText: 'SMC',
    badgeColor: '#b0bec5',
  },
  {
    symbol: 'CRUDEOIL FUT',
    displaySymbol: 'CRUDEOIL FUT',
    name: 'MCX WTI Crude Oil Futures (100 bbl)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 5980.0,
    tickSize: 1.0,
    precision: 2,
    badgeText: 'OIL',
    badgeColor: '#455a64',
  },
  {
    symbol: 'CRUDEOILM FUT',
    displaySymbol: 'CRUDEOILM FUT',
    name: 'MCX Crude Oil Mini Futures (10 bbl)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 5980.0,
    tickSize: 1.0,
    precision: 2,
    badgeText: 'CLM',
    badgeColor: '#455a64',
  },
  {
    symbol: 'NATURALGAS FUT',
    displaySymbol: 'NATURALGAS FUT',
    name: 'MCX Natural Gas Futures (1250 mmBtu)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 235.5,
    tickSize: 0.1,
    precision: 2,
    badgeText: 'GAS',
    badgeColor: '#ff7043',
  },
  {
    symbol: 'NATGASMINI FUT',
    displaySymbol: 'NATGASMINI FUT',
    name: 'MCX Natural Gas Mini Futures',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 235.5,
    tickSize: 0.1,
    precision: 2,
    badgeText: 'NGM',
    badgeColor: '#ff7043',
  },
  {
    symbol: 'COPPER FUT',
    displaySymbol: 'COPPER FUT',
    name: 'MCX Copper Futures (2.5 MT)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 815.0,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'CPR',
    badgeColor: '#d84315',
  },
  {
    symbol: 'ZINC FUT',
    displaySymbol: 'ZINC FUT',
    name: 'MCX Zinc Futures (5 MT)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 275.0,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'ZNC',
    badgeColor: '#78909c',
  },
  {
    symbol: 'ALUMINIUM FUT',
    displaySymbol: 'ALUMINIUM FUT',
    name: 'MCX Aluminium Futures (5 MT)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 230.0,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'ALU',
    badgeColor: '#90a4ae',
  },
  {
    symbol: 'LEAD FUT',
    displaySymbol: 'LEAD FUT',
    name: 'MCX Lead Futures (5 MT)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 180.0,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'LED',
    badgeColor: '#546e7a',
  },
  {
    symbol: 'MCXBULLDEX',
    displaySymbol: 'MCXBULLDEX',
    name: 'MCX Bullion Index (Gold & Silver)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 18200.0,
    tickSize: 1.0,
    precision: 2,
    badgeText: 'BUL',
    badgeColor: '#ff9800',
  },
  {
    symbol: 'MCXMETLDEX',
    displaySymbol: 'MCXMETLDEX',
    name: 'MCX Base Metals Index',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 19500.0,
    tickSize: 1.0,
    precision: 2,
    badgeText: 'MET',
    badgeColor: '#00bcd4',
  },
  {
    symbol: 'MCXENRGDEX',
    displaySymbol: 'MCXENRGDEX',
    name: 'MCX Energy Index (Crude & Gas)',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 5600.0,
    tickSize: 1.0,
    precision: 2,
    badgeText: 'ENR',
    badgeColor: '#e91e63',
  },
  {
    symbol: 'MCXCRUDEX',
    displaySymbol: 'MCXCRUDEX',
    name: 'MCX Crude Oil Index',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 5980.0,
    tickSize: 1.0,
    precision: 2,
    badgeText: 'CRU',
    badgeColor: '#455a64',
  },
  {
    symbol: 'MCXSILVDEX',
    displaySymbol: 'MCXSILVDEX',
    name: 'MCX Silver Index',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 89500.0,
    tickSize: 1.0,
    precision: 2,
    badgeText: 'SLV',
    badgeColor: '#b0bec5',
  },
  {
    symbol: 'MCXGOLDEX',
    displaySymbol: 'MCXGOLDEX',
    name: 'MCX Gold Index',
    exchange: 'MCX',
    category: 'commodities',
    feedType: 'openalgo',
    basePrice: 74500.0,
    tickSize: 1.0,
    precision: 2,
    badgeText: 'GLD',
    badgeColor: '#ffd700',
  },

  // ─── GLOBAL COMMODITIES & FOREX ────────────────────────────────────
  {
    symbol: 'PAXGUSDT',
    displaySymbol: 'GOLD (Spot)',
    name: 'Spot Gold USD',
    exchange: 'COMMODITY',
    category: 'commodities',
    feedType: 'commodity',
    basePrice: 4424.90,
    tickSize: 0.1,
    precision: 2,
    badgeText: '🥇',
    badgeColor: '#ffd700',
  },
  {
    symbol: 'XAGUSD',
    displaySymbol: 'SILVER (Spot)',
    name: 'Spot Silver USD',
    exchange: 'COMMODITY',
    category: 'commodities',
    feedType: 'commodity',
    basePrice: 67.15,
    tickSize: 0.01,
    precision: 2,
    badgeText: '🥈',
    badgeColor: '#b0bec5',
  },
  {
    symbol: 'CRUDEOIL',
    displaySymbol: 'CRUDE OIL',
    name: 'WTI Crude Oil ($/bbl)',
    exchange: 'NYMEX',
    category: 'commodities',
    feedType: 'commodity',
    basePrice: 96.08,
    tickSize: 0.01,
    precision: 2,
    badgeText: '🛢️',
    badgeColor: '#8d6e63',
  },
  {
    symbol: 'NATURALGAS',
    displaySymbol: 'NATURAL GAS',
    name: 'Henry Hub Natural Gas ($/MMBtu)',
    exchange: 'NYMEX',
    category: 'commodities',
    feedType: 'commodity',
    basePrice: 2.912,
    tickSize: 0.001,
    precision: 3,
    badgeText: '🔥',
    badgeColor: '#ff7043',
  },
  {
    symbol: 'USDINR',
    displaySymbol: 'USD / INR',
    name: 'US Dollar / Indian Rupee',
    exchange: 'FX',
    category: 'commodities',
    feedType: 'global',
    basePrice: 95.88,
    tickSize: 0.0025,
    precision: 4,
    badgeText: '💵',
    badgeColor: '#43a047',
  },
  {
    symbol: 'EURUSD',
    displaySymbol: 'EUR / USD',
    name: 'Euro / US Dollar',
    exchange: 'FX',
    category: 'commodities',
    feedType: 'global',
    basePrice: 1.1489,
    tickSize: 0.0001,
    precision: 4,
    badgeText: '💶',
    badgeColor: '#1e88e5',
  },
  {
    symbol: 'US10Y',
    displaySymbol: 'US 10Y YIELD',
    name: 'US 10 Year Benchmark Yield',
    exchange: 'BOND',
    category: 'commodities',
    feedType: 'global',
    basePrice: 4.998,
    tickSize: 0.001,
    precision: 3,
    badgeText: '📈',
    badgeColor: '#78909c',
  },
];

export function findInstrument(symbol) {
  if (!symbol) return null;
  const raw = symbol.toUpperCase().trim();
  const norm = raw.replace(/[^A-Z0-9]/g, '');

  const found = MASTER_INSTRUMENTS.find((item) => {
    const itemNorm = item.symbol.toUpperCase().replace(/[^A-Z0-9]/g, '');
    const itemDisp = item.displaySymbol.toUpperCase().replace(/[^A-Z0-9]/g, '');
    return itemNorm === norm || itemDisp === norm || item.symbol.toUpperCase() === raw;
  });

  if (found) return found;

  // Check commodity aliases or MCX contracts
  const isMcx =
    raw.includes('MCX') ||
    raw.startsWith('GOLD') ||
    raw.startsWith('SILVER') ||
    raw.startsWith('CRUDE') ||
    raw.startsWith('NATURALGAS') ||
    raw.startsWith('NATGAS') ||
    raw.startsWith('COPPER') ||
    raw.startsWith('ZINC') ||
    raw.startsWith('ALUMINIUM') ||
    raw.startsWith('LEAD');

  const isCrypto = norm.endsWith('USDT') || norm.endsWith('BTC') || norm.endsWith('ETH');
  const isFut = norm.includes('FUT');
  const cleanSym = raw.replace(/\.NS$/, '');

  return {
    symbol: cleanSym,
    displaySymbol: cleanSym,
    name: isMcx ? `${cleanSym} Commodity` : `${cleanSym} Stock`,
    exchange: isMcx ? 'MCX' : isCrypto ? 'BINANCE' : isFut ? 'NFO' : 'NSE',
    category: isMcx ? 'commodities' : isCrypto ? 'crypto' : isFut ? 'futures' : 'india',
    feedType: isCrypto ? 'binance' : 'openalgo',
    basePrice: isMcx ? 5000.0 : 1000.0,
    tickSize: isMcx ? 0.05 : 0.05,
    precision: 2,
    badgeText: cleanSym.slice(0, 2),
    badgeColor: isMcx ? '#ff9800' : '#2962ff',
  };
}
