/**
 * Zero Chart — Multi-Asset Instruments Registry & Watchlist Data
 * Dedicated categorized watchlists (NO "ALL" watchlist), comprehensive Indian stocks,
 * Futures, 24/7 Crypto, and Commodities.
 */

export const DEFAULT_WATCHLISTS = [
  {
    id: 'wl-stocks',
    name: 'Indian Stocks',
    symbols: [
      'MUTHOOTFIN',
      'ICICIBANK',
      'RELIANCE',
      'TCS',
      'HDFCBANK',
      'INFY',
      'TATAMOTORS',
      'SBIN',
      'AXISBANK',
      'KOTAKBANK',
      'BAJFINANCE',
      'LT',
      'ITC',
      'MARUTI',
      'TITAN',
      'ASIANPAINT',
      'SUNPHARMA',
      'TATASTEEL',
      'HAL',
      'BEL',
      'TRENT',
      'BSE',
      'CDSL',
      'JIOFIN',
    ],
  },
  {
    id: 'wl-indices',
    name: 'Indices & Futures',
    symbols: [
      'NIFTY 50',
      'BANKNIFTY',
      'FINNIFTY',
      'CNXAUTO',
      'CNXIT',
      'NIFTYMIDCAP',
      'SENSEX',
      'NIFTY FUT',
      'BANKNIFTY FUT',
    ],
  },
  {
    id: 'wl-crypto',
    name: '24/7 Crypto',
    symbols: [
      'BTCUSDT',
      'ETHUSDT',
      'SOLUSDT',
      'BNBUSDT',
      'XRPUSDT',
      'DOGEUSDT',
      'ADAUSDT',
      'LINKUSDT',
      'AVAXUSDT',
      'SUIUSDT',
    ],
  },
  {
    id: 'wl-commodities',
    name: 'Commodities & Forex',
    symbols: [
      'PAXGUSDT',
      'XAGUSD',
      'CRUDEOIL',
      'NATURALGAS',
      'USDINR',
      'EURUSD',
      'US10Y',
    ],
  },
];

export const MASTER_INSTRUMENTS = [
  // ─── INDIAN EQUITIES ───────────────────────────────────────────────
  {
    symbol: 'MUTHOOTFIN',
    displaySymbol: 'MUTHOOTFIN',
    name: 'Muthoot Finance Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 2836.90,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'MF',
    badgeColor: '#e53935',
  },
  {
    symbol: 'ICICIBANK',
    displaySymbol: 'ICICIBANK',
    name: 'ICICI Bank Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1342.40,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'IC',
    badgeColor: '#f57c00',
  },
  {
    symbol: 'RELIANCE',
    displaySymbol: 'RELIANCE',
    name: 'Reliance Industries Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1243.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'RE',
    badgeColor: '#2962ff',
  },
  {
    symbol: 'TCS',
    displaySymbol: 'TCS',
    name: 'Tata Consultancy Services',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 2121.10,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'TC',
    badgeColor: '#7c4dff',
  },
  {
    symbol: 'HDFCBANK',
    displaySymbol: 'HDFCBANK',
    name: 'HDFC Bank Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 726.85,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'HD',
    badgeColor: '#00897b',
  },
  {
    symbol: 'INFY',
    displaySymbol: 'INFY',
    name: 'Infosys Limited',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1044.40,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'IN',
    badgeColor: '#1e88e5',
  },
  {
    symbol: 'TATAMOTORS',
    displaySymbol: 'TATAMOTORS',
    name: 'Tata Motors Ltd. (TMPV)',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 304.75,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'TM',
    badgeColor: '#e53935',
  },
  {
    symbol: 'SBIN',
    displaySymbol: 'SBIN',
    name: 'State Bank of India',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 993.30,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'SB',
    badgeColor: '#3949ab',
  },
  {
    symbol: 'AXISBANK',
    displaySymbol: 'AXISBANK',
    name: 'Axis Bank Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1244.90,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'AX',
    badgeColor: '#880e4f',
  },
  {
    symbol: 'KOTAKBANK',
    displaySymbol: 'KOTAKBANK',
    name: 'Kotak Mahindra Bank',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1845.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'KB',
    badgeColor: '#d32f2f',
  },
  {
    symbol: 'BAJFINANCE',
    displaySymbol: 'BAJFINANCE',
    name: 'Bajaj Finance Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 7120.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'BF',
    badgeColor: '#0288d1',
  },
  {
    symbol: 'LT',
    displaySymbol: 'LT',
    name: 'Larsen & Toubro Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 3876.30,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'LT',
    badgeColor: '#fbc02d',
  },
  {
    symbol: 'ITC',
    displaySymbol: 'ITC',
    name: 'ITC Limited',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 485.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'IT',
    badgeColor: '#5d4037',
  },
  {
    symbol: 'MARUTI',
    displaySymbol: 'MARUTI',
    name: 'Maruti Suzuki India',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 12179.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'MS',
    badgeColor: '#00acc1',
  },
  {
    symbol: 'SUNPHARMA',
    displaySymbol: 'SUNPHARMA',
    name: 'Sun Pharmaceutical',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1847.40,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'SP',
    badgeColor: '#f57c00',
  },
  {
    symbol: 'TITAN',
    displaySymbol: 'TITAN',
    name: 'Titan Company Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 3580.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'TT',
    badgeColor: '#7b1fa2',
  },
  {
    symbol: 'ASIANPAINT',
    displaySymbol: 'ASIANPAINT',
    name: 'Asian Paints Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 2443.20,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'AP',
    badgeColor: '#e91e63',
  },
  {
    symbol: 'TATASTEEL',
    displaySymbol: 'TATASTEEL',
    name: 'Tata Steel Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 187.48,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'TS',
    badgeColor: '#546e7a',
  },
  {
    symbol: 'HAL',
    displaySymbol: 'HAL',
    name: 'Hindustan Aeronautics',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 4860.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'HL',
    badgeColor: '#00838f',
  },
  {
    symbol: 'BEL',
    displaySymbol: 'BEL',
    name: 'Bharat Electronics Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 398.60,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'BE',
    badgeColor: '#2e7d32',
  },
  {
    symbol: 'TRENT',
    displaySymbol: 'TRENT',
    name: 'Trent Ltd.',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 2799.90,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'TR',
    badgeColor: '#6a1b9a',
  },
  {
    symbol: 'BSE',
    displaySymbol: 'BSE',
    name: 'BSE Limited',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 3264.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'BS',
    badgeColor: '#c2185b',
  },
  {
    symbol: 'CDSL',
    displaySymbol: 'CDSL',
    name: 'Central Depository Services',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 1373.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'CD',
    badgeColor: '#512da8',
  },
  {
    symbol: 'JIOFIN',
    displaySymbol: 'JIOFIN',
    name: 'Jio Financial Services',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 335.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'JF',
    badgeColor: '#00bcd4',
  },

  // ─── INDIAN INDICES & FUTURES ──────────────────────────────────────
  {
    symbol: 'NIFTY 50',
    displaySymbol: 'NIFTY',
    name: 'Nifty 50 Index',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 23324.90,
    tickSize: 0.05,
    precision: 2,
    badgeText: '50',
    badgeColor: '#2962ff',
  },
  {
    symbol: 'BANKNIFTY',
    displaySymbol: 'BANKNIFTY',
    name: 'Nifty Bank Index',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 56248.75,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'BK',
    badgeColor: '#1e53e5',
  },
  {
    symbol: 'FINNIFTY',
    displaySymbol: 'FINNIFTY',
    name: 'Nifty Financial Services',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 25469.10,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'FN',
    badgeColor: '#089981',
  },
  {
    symbol: 'CNXAUTO',
    displaySymbol: 'CNXAUTO',
    name: 'Nifty Auto Index',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 27232.55,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'AU',
    badgeColor: '#e040fb',
  },
  {
    symbol: 'NIFTYMIDCAP',
    displaySymbol: 'NIFTY MIDCAP',
    name: 'Nifty Midcap 50 Index',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 17784.30,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'MC',
    badgeColor: '#ff9800',
  },
  {
    symbol: 'CNXIT',
    displaySymbol: 'CNXIT',
    name: 'Nifty IT Index',
    exchange: 'NSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 28664.15,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'IT',
    badgeColor: '#00bcd4',
  },
  {
    symbol: 'SENSEX',
    displaySymbol: 'SENSEX',
    name: 'BSE Sensex Index',
    exchange: 'BSE',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 74467.15,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'SX',
    badgeColor: '#ff5252',
  },
  {
    symbol: 'NIFTY FUT',
    displaySymbol: 'NIFTY FUT',
    name: 'Nifty 50 Index Futures',
    exchange: 'NFO',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 23360.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'NF',
    badgeColor: '#2962ff',
  },
  {
    symbol: 'BANKNIFTY FUT',
    displaySymbol: 'BANKNIFTY FUT',
    name: 'Bank Nifty Futures',
    exchange: 'NFO',
    category: 'india',
    feedType: 'openalgo',
    basePrice: 56310.00,
    tickSize: 0.05,
    precision: 2,
    badgeText: 'BF',
    badgeColor: '#1e53e5',
  },

  // ─── 24/7 LIVE CRYPTO ──────────────────────────────────────────────
  {
    symbol: 'BTCUSDT',
    displaySymbol: 'BTC / USDT',
    name: 'Bitcoin',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 68540.00,
    tickSize: 0.01,
    precision: 2,
    badgeText: '₿',
    badgeColor: '#f7931a',
  },
  {
    symbol: 'ETHUSDT',
    displaySymbol: 'ETH / USDT',
    name: 'Ethereum',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 3485.20,
    tickSize: 0.01,
    precision: 2,
    badgeText: 'Ξ',
    badgeColor: '#627eea',
  },
  {
    symbol: 'SOLUSDT',
    displaySymbol: 'SOL / USDT',
    name: 'Solana',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 156.80,
    tickSize: 0.01,
    precision: 2,
    badgeText: '◎',
    badgeColor: '#14f195',
  },
  {
    symbol: 'BNBUSDT',
    displaySymbol: 'BNB / USDT',
    name: 'BNB Coin',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 582.40,
    tickSize: 0.1,
    precision: 2,
    badgeText: '🔶',
    badgeColor: '#f3ba2f',
  },
  {
    symbol: 'XRPUSDT',
    displaySymbol: 'XRP / USDT',
    name: 'Ripple',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 0.5890,
    tickSize: 0.0001,
    precision: 4,
    badgeText: '✕',
    badgeColor: '#546e7a',
  },
  {
    symbol: 'DOGEUSDT',
    displaySymbol: 'DOGE / USDT',
    name: 'Dogecoin',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 0.1085,
    tickSize: 0.0001,
    precision: 4,
    badgeText: 'Ð',
    badgeColor: '#c2a633',
  },
  {
    symbol: 'ADAUSDT',
    displaySymbol: 'ADA / USDT',
    name: 'Cardano',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 0.3550,
    tickSize: 0.0001,
    precision: 4,
    badgeText: '₳',
    badgeColor: '#0033ad',
  },
  {
    symbol: 'LINKUSDT',
    displaySymbol: 'LINK / USDT',
    name: 'Chainlink',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 11.45,
    tickSize: 0.01,
    precision: 2,
    badgeText: '⬡',
    badgeColor: '#375bd2',
  },
  {
    symbol: 'AVAXUSDT',
    displaySymbol: 'AVAX / USDT',
    name: 'Avalanche',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 28.30,
    tickSize: 0.01,
    precision: 2,
    badgeText: '🔺',
    badgeColor: '#e84142',
  },
  {
    symbol: 'SUIUSDT',
    displaySymbol: 'SUI / USDT',
    name: 'Sui Network',
    exchange: 'BINANCE',
    category: 'crypto',
    feedType: 'binance',
    basePrice: 1.54,
    tickSize: 0.0001,
    precision: 4,
    badgeText: '💧',
    badgeColor: '#4ca2fe',
  },

  // ─── COMMODITIES & FOREX ───────────────────────────────────────────
  {
    symbol: 'PAXGUSDT',
    displaySymbol: 'GOLD (Spot)',
    name: 'Spot Gold USD',
    exchange: 'COMMODITY',
    category: 'commodities',
    feedType: 'commodity',
    basePrice: 2584.20,
    tickSize: 0.1,
    precision: 2,
    badgeText: '🥇',
    badgeColor: '#ffd700',
  },
  {
    symbol: 'XAGUSD',
    displaySymbol: 'SILVER (Spot)',
    name: 'Spot Silver USD',
    exchange: 'COMMODITY',
    category: 'commodities',
    feedType: 'commodity',
    basePrice: 31.65,
    tickSize: 0.01,
    precision: 2,
    badgeText: '🥈',
    badgeColor: '#b0bec5',
  },
  {
    symbol: 'CRUDEOIL',
    displaySymbol: 'CRUDE OIL',
    name: 'WTI Crude Oil ($/bbl)',
    exchange: 'NYMEX',
    category: 'commodities',
    feedType: 'commodity',
    basePrice: 71.95,
    tickSize: 0.01,
    precision: 2,
    badgeText: '🛢️',
    badgeColor: '#8d6e63',
  },
  {
    symbol: 'NATURALGAS',
    displaySymbol: 'NATURAL GAS',
    name: 'Henry Hub Natural Gas ($/MMBtu)',
    exchange: 'NYMEX',
    category: 'commodities',
    feedType: 'commodity',
    basePrice: 2.385,
    tickSize: 0.001,
    precision: 3,
    badgeText: '🔥',
    badgeColor: '#ff7043',
  },
  {
    symbol: 'USDINR',
    displaySymbol: 'USD / INR',
    name: 'US Dollar / Indian Rupee',
    exchange: 'FX',
    category: 'commodities',
    feedType: 'global',
    basePrice: 83.6525,
    tickSize: 0.0025,
    precision: 4,
    badgeText: '💵',
    badgeColor: '#43a047',
  },
  {
    symbol: 'EURUSD',
    displaySymbol: 'EUR / USD',
    name: 'Euro / US Dollar',
    exchange: 'FX',
    category: 'commodities',
    feedType: 'global',
    basePrice: 1.1152,
    tickSize: 0.0001,
    precision: 4,
    badgeText: '💶',
    badgeColor: '#1e88e5',
  },
  {
    symbol: 'US10Y',
    displaySymbol: 'US 10Y YIELD',
    name: 'US 10 Year Benchmark Yield',
    exchange: 'BOND',
    category: 'commodities',
    feedType: 'global',
    basePrice: 4.931,
    tickSize: 0.001,
    precision: 3,
    badgeText: '📈',
    badgeColor: '#78909c',
  },
];

export function findInstrument(symbol) {
  if (!symbol) return null;
  const norm = symbol.toUpperCase().replace(/[^A-Z0-9]/g, '');
  const found = MASTER_INSTRUMENTS.find((item) => {
    const itemNorm = item.symbol.toUpperCase().replace(/[^A-Z0-9]/g, '');
    const itemDisp = item.displaySymbol.toUpperCase().replace(/[^A-Z0-9]/g, '');
    return itemNorm === norm || itemDisp === norm || item.symbol.toUpperCase() === symbol.toUpperCase();
  });

  if (found) return found;

  // Dynamic instrument creation for any unlisted searched symbol
  const isCrypto = norm.endsWith('USDT') || norm.endsWith('BTC') || norm.endsWith('ETH');
  const isFut = norm.includes('FUT');
  const cleanSym = symbol.toUpperCase().replace(/\.NS$/, '');
  return {
    symbol: cleanSym,
    displaySymbol: cleanSym,
    name: `${cleanSym} Stock`,
    exchange: isCrypto ? 'BINANCE' : isFut ? 'NFO' : 'NSE',
    category: isCrypto ? 'crypto' : 'india',
    feedType: isCrypto ? 'binance' : 'openalgo',
    basePrice: 1000.0,
    tickSize: 0.05,
    precision: 2,
    badgeText: cleanSym.slice(0, 2),
    badgeColor: '#2962ff',
  };
}
